import Footer from "components/Footer";
import Navbar from "components/Navbar";
import Head from "next/head";
import Link from "next/link";
import styles from "../styles/Home.module.css";

export default function Home() {
  return (
    <>
      <Head>
        <title>Ecommerce | Home</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className="content">
        <div className="homepage-text">
         <h1>Ecommerce Front Page</h1>
          <p>
            Lorem ipsum dolor sit amet consectetur, adipisicing elit. Eveniet
            laboriosam consequatur aspernatur molestias, voluptas accusantium
            similique sed sint ducimus minima in accusamus dolorem rerum commodi
            dicta non iste reiciendis nihil?
          </p>
         <Link href="/shop"><button>Shop Now</button></Link>
        </div>
        <img src="/front-page-img.png" alt="" width={496} />
      </div>
    </>
  );
}
